spring:
  application:
    name: shows

  cloud:
    stream:
      bindings:
        actorChanges:
          group: shows

info:
  name: ${spring.application.name}
  version: ${version}

server:
  port: 8011

endpoints:
  shutdown:
    sensitive: false
    enabled: true
  health:
    sensitive: false

feign:
  hystrix:
    enabled: false

hystrix:
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 2000
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 500

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    registryFetchIntervalSeconds: 2
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/